#!/bin/bash

# Determinate the subject user - $USR
USR="$(id -u)"

# Get the most frequent value of any array
get_frequent(){
    awk 'BEGIN{FS=" "} {for(i=1;i<=NF;i++) print $i}' | \
    awk '
      {
          n=++hsh[$1]
          if(n>max_occ){
             max_occ=n
             what=$1
          }else if(n==max_occ){
             if(what>$1)
                 what=$1
          }
      }
      END { print what }
    '
}

# Get the numbers of all $USR's processes
PS=`pgrep -U "${USR}"`
 
# Get the values of $XDG_CURRENT_DESKTOP, $GDMSESSION, $DESKTOP_SESSION from each "/proc/$ProcessNumber/environ" file
for PN in $PS; do
        XDG_CURRENT_DESKTOP+=$(sed -zne 's/^XDG_CURRENT_DESKTOP=//p' "/proc/$PN/environ" 2>/dev/null | tr '\0' '\n'; echo " ")
        GDMSESSION+=$(sed -zne 's/^GDMSESSION=//p' "/proc/$PN/environ" 2>/dev/null | tr '\0' '\n'; echo " ")
        DESKTOP_SESSION+=$(sed -zne 's/^DESKTOP_SESSION=//p' "/proc/$PN/environ" 2>/dev/null | tr '\0' '\n'; echo " ")
done

# Get the most frequent name of any desktop environment
# This is a way to find the current DE when it is changed a little bit ago
XDG_CURRENT_DESKTOP=$(echo -e ${XDG_CURRENT_DESKTOP[@]} | get_frequent)
GDMSESSION=$(echo -e ${GDMSESSION[@]} | get_frequent)
DESKTOP_SESSION=$(echo -e ${DESKTOP_SESSION[@]} | get_frequent)

# Setting the desktop environment
export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP[@]^}"
export GDMSESSION="${GDMSESSION[@]^}"
export DESKTOP_SESSION="${DESKTOP_SESSION[@]^}"

#Run ADMC
admc